name: CI Test HTML

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Vérification du HTML
        run: echo "CI déclenchée avec succès !"
